# Generated by Django 4.2.1 on 2023-08-02 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_alter_news_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 2, 11, 56, 30, 38427, tzinfo=datetime.timezone.utc)),
        ),
    ]
